# .github/workflows/deploy-azure.yml
name: Deploy API to Azure
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: TaskTrackerApp    # Replace with your app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'             # Match your .NET version
  PROJECT_PATH: './TaskTrackerApp.API.NETCore'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.PROJECT_PATH }}
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.PROJECT_PATH }}
    
    - name: Run Tests
      run: dotnet test --configuration Release --no-restore --verbosity normal --logger trx --results-directory ./TestResults
      working-directory: ${{ env.PROJECT_PATH }}
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ${{ env.PROJECT_PATH }}/TestResults/*.trx
    
    - name: Publish
      run: dotnet publish -c Release -o ${{github.workspace}}/myapp
      working-directory: ${{ env.PROJECT_PATH }}
    
    - name: Debug - List publish output
      run: |
        echo "Checking if myapp directory exists..."
        ls -la ${{github.workspace}}/
        echo "---"
        echo "Contents of myapp directory:"
        ls -la ${{github.workspace}}/myapp/ || echo "myapp directory not found!"
        echo "---"
        echo "DLL files in myapp:"
        find ${{github.workspace}}/myapp/ -name "*.dll" || echo "No DLL files found"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{github.workspace}}/myapp
        slot-name: 